# Generated by Django 5.0.7 on 2024-08-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_buyer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='balance',
            field=models.DecimalField(decimal_places=100, max_digits=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='cost',
            field=models.DecimalField(decimal_places=100, max_digits=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='field_fractional_numbers',
            field=models.DecimalField(decimal_places=100, max_digits=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='size',
            field=models.DecimalField(decimal_places=100, max_digits=100),
        ),
    ]
